functionality:
  name: project_debug
  namespace: viash
  version: 0.1
  description: |
    Generate debugging report based on viash ns test output
  arguments:
  - name: "--input"
    type: file
    required: true
    description: viasn ns test output file (tsv format)
  - name: "--tmp"
    type: file
    default: /tmp
    description: System temp dir if different from /tmp (e.g. on Mac use /private/tmp)
  - name: "--output"
    type: file
    direction: output
    default: debug_report.md
    description: Name/path of the output markdown file
  resources:
  - type: bash_script
    path: ./code.sh
platforms:
- type: native
- type: docker
  image: dataintuitive/viash:0.4.0-rc1
