functionality:
  name: viash_nxf_schema
  namespace: viash
  version: 0.1
  description: |
    Generate a Nextflow schema file based on a workflow config.
    See https://nf-co.re/pipeline_schema_builder
  arguments:
  - name: "--config"
    alternatives: [ -i, --input ]
    type: file
    default: config.vsh.yaml
    description: A Viash config for a workflow
  - name: "--schema"
    alternatives: [ -o, --output ]
    type: file
    default: nextflow_schema.json
    description: nextflow schema file
  resources:
  - type: bash_script
    path: ./script.sh
  - path: template.j2
  tests:
  - type: bash_script
    path: tests.sh
platforms:
- type: native
- type: docker
  image: python:3.8
  python:
    packages: [ jinja-cli, nf-core ]
