name: Scala CI

on: [push, pull_request]

jobs:
  scala-ci:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'main', os: ubuntu-latest }
        - {name: 'macos_latest', os: macos-latest }

    steps:
    - uses: actions/checkout@v2

    - name: Set up nextflow
      if: runner.os == 'Linux'
      run: |
        mkdir -p "$HOME/.local/bin"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        curl -s https://get.nextflow.io | bash
        mv nextflow "$HOME/.local/bin"
        nextflow -version
        NXF_VER=21.04.1 nextflow run hello

    - name: Set up sbt
      uses: olafurpg/setup-scala@v10

    - name: Run tests
      run: |
        if [[ "${{ matrix.config.name }}" == "main" ]]; then
          # only run coverage on main runner
          sbt clean coverage test coverageReport
        elif [[ "${{ matrix.config.os }}" =~ ^macos.*$ ]]; then
          # macOS on github actions does not have Docker, so skip those
          sbt 'testOnly -- -l com.dataintuitive.viash.DockerTest'
        else
          sbt test
        fi

    - name: Upload coverage on success
      run: bash <(curl -s https://codecov.io/bash)

    - name: Upload check results on fail
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check
